### ISSUE TITLE
unsquash -li does not write all files in an archive

### ISSUE THREAD

**Issue by juanitotc** [plougher/squashfs-tools#76] opened 2019-10-21 12:49 UTC
After updating to squashfs-tools-4.4, unsquashfs -li does not write all of the files in an archive:

`$ unsquashfs -li qt-5.x-xml.tcz
Parallel unsquashfs: Using 4 processors
8 inodes (702 blocks) to write

drwxr-xr-x tc/staff                 26 2019-10-10 12:34 squashfs-root
drwxr-xr-x root/root                28 2019-10-10 12:01 squashfs-root/usr
drwxr-xr-x root/root                26 2019-10-10 12:34 squashfs-root/usr/local
drwxr-xr-x root/root               235 2019-10-10 12:35 squashfs-root/usr/local/lib
lrwxrwxrwx root/root                19 2019-10-10 12:34 squashfs-root/usr/local/lib/libQt5Xml.so -> libQt5Xml.so.5.11.2
lrwxrwxrwx root/root                19 2019-10-10 12:34 squashfs-root/usr/local/lib/libQt5Xml.so.5 -> libQt5Xml.so.5.11.2
lrwxrwxrwx root/root                19 2019-10-10 12:34 squashfs-root/usr/local/lib/libQt5Xml.so.5.11 -> libQt5Xml.so.5.11.2
-rwxr-xr-x root/root            165644 2019-10-10 09:54 squashfs-root/usr/local/lib/libQt5Xml.so.5.11.2
lrwxrwxrwx root/root                27 2019-10-10 12:34 squashfs-root/usr/local/lib/libQt5XmlPatterns.so -> libQt5XmlPatterns.so.5.11.2
lrwxrwxrwx root/root                27 2019-10-10 12:34 squashfs-root/usr/local/lib/libQt5XmlPatterns.so.5 -> libQt5XmlPatterns.so.5.11.2
lrwxrwxrwx root/root                27 2019-10-10 12:34 squashfs-root/usr/local/lib/libQt5XmlPatterns.so.5.11 -> libQt5XmlPatterns.so.5.11.2
-rwxr-xr-x root/root           2681820 2019-10-10 09:55 squashfs-root/usr/local/lib/libQt5XmlPatterns.so.5.11.2`

..but 

`$ ls squashfs-root/usr/local/lib
libQt5Xml.so               libQt5XmlPatterns.so
libQt5Xml.so.5             libQt5XmlPatterns.so.5
libQt5Xml.so.5.11          libQt5XmlPatterns.so.5.11
libQt5Xml.so.5.11.2`

..i.e. libQt5XmlPatterns.so.5.11.2 is missing even though it is present in the archive

**Comment by plougher** [comment] 2020-10-30 13:22
I cannot reproduce this, and no changes in Squashfs 4.4. are expected to have produced such a failure.

Without more information or a reproducer filesystem, this cannot be verified.

As issue has been dormant for over a year closing.

**Closed by plougher** 2020-10-30 13:22 UTC
