### ISSUE TITLE
Versions 4.4 and 4.5 may now refuse to unsquash filesystems with xattrs

### ISSUE THREAD

**Issue by danfe** [plougher/squashfs-tools#120] opened 2021-07-26 02:18 UTC
It had been [brought to my attention](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256790) that since version 4.4 `unsquashfs` refuses to work with filesystems with extended attributes (e.g. `attr -s foo -V bar somefile`), while version 4.3 handled them just fine, by ignoring the attributes upon extraction.  This is on FreeBSD which `squashfs-tools` do not currently support XATTRs on, so we've always been building with `XATTR_SUPPORT` commented out.

This behavior is not just inconvenient, it also contradicts the usage information, which clearly says (in our case) that `unsquashfs` won't be extracting extended attributes by default:
```
    -no[-xattrs]            don't extract xattrs in file system (default)
    -x[attrs]               extract xattrs in file system (unsupported)
```

**Comment by plougher** [comment] 2022-01-27 06:50
This is a regression (introduced in 2019) caused by extra sanity checking (security hardening) of the filesystem.  Specifically,
to do the extra sanity checking, Unsquashfs needs to partially parse the xattr table metadata, and without any xattr support,
the necessary code doesn't exist, and so Unsquashfs aborts when calling the dummy no-xattr support function (which just returns failure).

The solution is to partially read the xattr metadata in the no-support function, to obtain the necessary information required by the extra sanity checks.

This has been fixed by the above commit.

**Closed by plougher** 2022-01-27 06:50 UTC
